[mypy]

[mypy-jack_pulse.*]
ignore_missing_imports = True

[mypy-download.*]
ignore_missing_imports = True

[mypy-secretstorage.*]
ignore_missing_imports = True

[mypy-keyring.*]
ignore_missing_imports = True

[mypy-bsddb3.*]
ignore_missing_imports = True

[mypy-imap.*]
ignore_missing_imports = True
