#!/usr/bin/env python

"""
Generate pyproject.toml from the [dependencies] pip table in
rsconstruct.toml.

rsconstruct.toml is the single source of truth for this repo's runtime
dependencies: it is what CI installs via `rsconstruct tools install-deps`.
pyproject.toml exists only so `uv sync` has something to read, so it is
generated rather than maintained by hand.
"""

import sys
import tomllib

SOURCE = "rsconstruct.toml"
OUTPUT = "pyproject.toml"
# Without this uv warns on every `uv sync` and silently defaults to the
# running interpreter's version, which makes resolution depend on whichever
# python happens to be first on PATH.
REQUIRES_PYTHON = "3.14"

HEADER = """\
# Generated by scripts/gen_pyproject.py from rsconstruct.toml -- do not
# edit by hand. Add dependencies to the [dependencies] pip table there.
#
# This repo is not a distribution: it is standalone scripts under src/, plus
# local support packages that sit beside them. There is nothing to build a
# wheel from, hence `package = false` and no [build-system] table. The
# [project] table exists only because uv requires name, version and
# requires-python to resolve.
"""


def main() -> int:
    with open(SOURCE, "rb") as stream:
        config = tomllib.load(stream)
    deps = config.get("dependencies", {}).get("pip", [])
    if not deps:
        print(f"no [dependencies] pip entries in {SOURCE}", file=sys.stderr)
        return 1
    lines = [
        HEADER,
        "",
        "[project]",
        'name = "utils-python"',
        'version = "0.0.0"',
        f'requires-python = ">={REQUIRES_PYTHON}"',
        "dependencies = [",
    ]
    lines.extend(f'    "{dep}",' for dep in deps)
    lines.extend(["]", "", "[tool.uv]", "package = false", ""])
    with open(OUTPUT, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
