#!/usr/bin/python

"""
Generate pyproject.toml from the [dependencies] pip table in
rsconstruct.local.toml.

rsconstruct.local.toml is the single source of truth for this repo's runtime
dependencies: it is what CI installs via `rsconstruct tools install-deps`.
pyproject.toml exists only so `uv sync` has something to read, so it is
generated rather than maintained by hand.
"""

import sys

import tomllib

SOURCE = "rsconstruct.local.toml"
OUTPUT = "pyproject.toml"

HEADER = """\
# Generated by scripts/gen_pyproject.py from rsconstruct.local.toml -- do not
# edit by hand. Add dependencies to the [dependencies] pip table there.
#
# This repo is not a distribution: it is standalone scripts under src/, plus
# local support packages that sit beside them. There is nothing to build a
# wheel from, hence `package = false` and no [build-system] table. The
# [project] table exists only because uv requires name and version to resolve.
"""


def main() -> int:
    with open(SOURCE, "rb") as stream:
        config = tomllib.load(stream)
    deps = config.get("dependencies", {}).get("pip", [])
    if not deps:
        print(f"no [dependencies] pip entries in {SOURCE}", file=sys.stderr)
        return 1
    lines = [HEADER, "", "[project]", 'name = "utils-python"', 'version = "0.0.0"', "dependencies = ["]
    lines.extend(f'    "{dep}",' for dep in deps)
    lines.extend(["]", "", "[tool.uv]", "package = false", ""])
    with open(OUTPUT, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
